# Generated by Django 5.0.6 on 2024-05-25 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='grupo_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='mi_aplicacion.grupo'),
        ),
    ]
