# Generated by Django 5.0.6 on 2024-05-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_profesor_grupo_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='con_quien_vives',
            field=models.CharField(choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dependes_economicamente',
            field=models.CharField(choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Tú', 'Tú'), ('Otros', 'Otros')], max_length=20),
        ),
    ]
