# Generated by Django 5.0.6 on 2024-06-03 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_alter_estudiante_con_quien_vives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='actividad_hermanos',
            field=models.TextField(blank=True, null=True, verbose_name='Actividad de los hermanos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ayuda_psicologica',
            field=models.BooleanField(verbose_name='¿Recibes ayuda psicológica?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='beca_bachillerato',
            field=models.BooleanField(verbose_name='¿Tuviste beca en el bachillerato? si la respuesta es SI marca la casilla'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cantidad_libros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad de libros de apoyo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carrera_primera_opcion',
            field=models.BooleanField(verbose_name='¿Es esta carrera tu primera opción?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Teléfono Celular'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='computadora_internet',
            field=models.BooleanField(verbose_name='¿Tienes computadora con internet?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='con_quien_vives',
            field=models.CharField(choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Ambos', 'Ambos'), ('Otros', 'Otros')], max_length=20, verbose_name='¿Con quién vives?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo_electronico',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cual_espacio_estudio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Cuál es tu espacio de estudio?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cual_otra_escuela',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿En qué otra escuela estudiaste?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cual_tecnica_estudio',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuál técnica de estudio?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cuales_materias_reprobadas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Cuáles materias reprobaste?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cualidades',
            field=models.TextField(blank=True, null=True, verbose_name='Cualidades'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cuatrimestre',
            field=models.CharField(max_length=100, verbose_name='Cuatrimestre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='debilidades',
            field=models.TextField(blank=True, null=True, verbose_name='Debilidades'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dependes_economicamente',
            field=models.CharField(choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Tú', 'Tú'), ('Ambos', 'Ambos'), ('Otros', 'Otros')], max_length=20, verbose_name='¿De quién dependes económicamente?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dependientes_economicos',
            field=models.TextField(blank=True, null=True, verbose_name='Dependientes económicos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='direccion',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='discapacidad',
            field=models.BooleanField(verbose_name='¿Tienes alguna discapacidad?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='disgustos',
            field=models.TextField(blank=True, null=True, verbose_name='Disgustos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='escuela_procedencia',
            field=models.CharField(max_length=200, verbose_name='Escuela de procedencia'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='espacio_estudio',
            field=models.BooleanField(verbose_name='¿Tienes un espacio adecuado para estudiar?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='especialidad_promedio',
            field=models.CharField(max_length=100, verbose_name='Especialidad y promedio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Otro', 'Otro')], max_length=10, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_civil_otro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro (estado civil)'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_salud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de salud'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='examen_admision',
            field=models.BooleanField(verbose_name='¿Realizaste el examen de admisión?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='expectativas_carrera',
            field=models.TextField(blank=True, null=True, verbose_name='Expectativas de la carrera'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='forma_trabajar',
            field=models.CharField(choices=[('Solo', 'Solo'), ('En equipo', 'En equipo'), ('Binas', 'Binas'), ('Grupal', 'Grupal')], max_length=10, verbose_name='Forma de trabajar'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='futuro_academico',
            field=models.TextField(blank=True, null=True, verbose_name='Futuro académico'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='futuro_personal',
            field=models.TextField(blank=True, null=True, verbose_name='Futuro personal'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='futuro_profesional',
            field=models.TextField(blank=True, null=True, verbose_name='Futuro profesional'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grupo_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.grupo', verbose_name='Grupo escolar'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='habilidades',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidades'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='hermanos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de hermanos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='horario_laboral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario laboral'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='horas_trabajo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas de trabajo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ingreso_madre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso de la madre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ingreso_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso mensual'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ingreso_padre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso del padre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='libros_apoyo',
            field=models.BooleanField(verbose_name='¿Usas libros de apoyo?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lugar_entre_hermanos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar entre hermanos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lugar_nacimiento',
            field=models.CharField(max_length=200, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lugar_procedencia',
            field=models.CharField(max_length=200, verbose_name='Lugar de procedencia'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='materias_dificultad',
            field=models.TextField(blank=True, null=True, verbose_name='Materias con dificultad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='materias_facil',
            field=models.TextField(blank=True, null=True, verbose_name='Materias fáciles'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='materias_reprobadas',
            field=models.BooleanField(verbose_name='¿Reprobaste materias?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='motivacion_estudio',
            field=models.BooleanField(verbose_name='¿Tienes motivación para estudiar?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='motivo_ayuda',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de la ayuda psicológica'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='motivo_beca',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de la beca'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='motivo_carrera_opcion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo para elegir esta opción de carrera'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='motivo_forma_trabajar',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo para la forma de trabajar'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='motivo_motivacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de la motivación'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='motivo_universidad',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo para elegir esta universidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='motivo_universidad_opcion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo para elegir esta opción de universidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre_tutor',
            field=models.CharField(max_length=200, verbose_name='Nombre del tutor'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numero_matricula',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de matrícula'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numero_seguro_social',
            field=models.CharField(max_length=20, verbose_name='Número de seguro social'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ocupacion_madre',
            field=models.CharField(max_length=100, verbose_name='Ocupación de la madre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ocupacion_padre',
            field=models.CharField(max_length=100, verbose_name='Ocupación del padre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='otros_dependientes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Otros dependientes'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='otros_familiares',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Otros familiares'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='pareja_sentimental',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pareja sentimental'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='planes_matrimonio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Planes de matrimonio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='planes_terminar_carrera',
            field=models.TextField(blank=True, null=True, verbose_name='Planes para terminar la carrera'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='problemas_personales',
            field=models.TextField(blank=True, null=True, verbose_name='Problemas personales'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='requieres_beca',
            field=models.BooleanField(verbose_name='¿Requieres beca? si la respuesta es SI marac la casilla'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tecnica_estudio',
            field=models.BooleanField(verbose_name='¿Usas alguna técnica de estudio?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono Casa'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_emergencia',
            field=models.CharField(max_length=15, verbose_name='Teléfono de emergencia'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='temores',
            field=models.TextField(blank=True, null=True, verbose_name='Temores'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tiempo_libre',
            field=models.TextField(blank=True, null=True, verbose_name='Tiempo libre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_beca_bachillerato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de beca en bachillerato'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_casa',
            field=models.CharField(choices=[('Propia', 'Propia'), ('Rentada', 'Rentada'), ('Prestada', 'Prestada'), ('Otros', 'Otros')], max_length=10, verbose_name='Tipo de casa'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_casa_otros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otros (tipo de casa)'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_computadora',
            field=models.CharField(blank=True, choices=[('PC', 'PC'), ('Laptop', 'Laptop')], max_length=10, null=True, verbose_name='Tipo de computadora'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_discapacidad',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de discapacidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de empresa'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_internet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de conexión a internet'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_religion',
            field=models.CharField(max_length=100, verbose_name='Tipo de religión'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_sangre',
            field=models.CharField(max_length=3, verbose_name='Tipo de sangre'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_trabajo',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de trabajo que te gustaría tener'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_tratamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de tratamiento médico'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='trabajas',
            field=models.BooleanField(verbose_name='¿Trabajas? si la respuesta es SI marca la casilla en caso contrario omite las siguientes preguntas'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='transporte_universidad',
            field=models.TextField(blank=True, null=True, verbose_name='Transporte a la universidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tratamiento_medico',
            field=models.BooleanField(verbose_name='¿Estás en tratamiento médico?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='universidad_primera_opcion',
            field=models.BooleanField(verbose_name='¿Es esta universidad tu primera opción?'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='valores',
            field=models.TextField(blank=True, null=True, verbose_name='Valores'),
        ),
    ]
